name: Elm CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Elm and tools
        run: |
          npm install

      - name: Run Elm Format
        run: |
          npx elm-format src --yes

      - name: Run Elm Analyse
        run: |
          npx elm-analyse

      - name: Run Elm Tests
        run: |
          npx elm-test
        