name: Elm CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Navigate to frontend and install dependencies
        working-directory: ./frontend
        run: |
          npm install

      - name: Run Elm Format
        working-directory: ./frontend
        run: |
          npx elm-format src --yes
